name: CI Testing

on:
  push:
    branches:
    - main

jobs:
  testing:
    name: Testing GH Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test Contexts
        shell: bash
        run: echo ${{ secrets.SECRET_WORD }}
        
