name: CI Testing

on:
  push:
    branches:
    - main

jobs:
  testing:
    name: Testing GH Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get PR Title
        uses: actions/github-script@v7
        id: pr-data
        with:
          script: |
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0];
        
      - name: Test Contexts
        shell: bash
        run: |
          echo ${{ secrets.SECRET_WORD }} &&
          echo ${{ github.event.repository.name }} &&
          echo ${{ github.event.repository.full_name }} &&
          echo ${{ github.event.repository.html_url }} &&
          echo ${{ github.repositoryUrl }} &&
          echo ${{ github.repository.name }} &&
          
          echo ${{ github.repository.full_name }} &&
          echo ${{ github.actor }} &&
          echo ${{ github.event.pull_request.title }} &&
          echo ${{ fromJson(steps.pr-data.outputs.result).title }}
